package com.iishanto.jobhunterbackend.infrastructure.google;

import com.iishanto.jobhunterbackend.domain.model.SimpleUserModel;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class GoogleIdTokenVerifierTest {
    @Autowired
    GoogleIdTokenVerifier googleIdTokenVerifier;
    @Test
    void verifyIdToken(){
        String idToken="eyJhbGciOiJSUzI1NiIsImtpZCI6IjA3YjgwYTM2NTQyODUyNWY4YmY3Y2QwODQ2ZDc0YThlZTRlZjM2MjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI3NDI4Mjc0MTk4ODktcGlnZWJqdGRiZTF2dXUxNWRnbDU4MDhvNWpkN2luazMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI3NDI4Mjc0MTk4ODktcGlnZWJqdGRiZTF2dXUxNWRnbDU4MDhvNWpkN2luazMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDE1NjMwODg2MzA5NzYwMjk0MDAiLCJlbWFpbCI6Im1lLnNoYXJpZi5oYXNhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmJmIjoxNzQ2NTQ1ODUxLCJuYW1lIjoiU2hhcmlmIEhhc2FuIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0xFLXBLUXg1Zm9BcTdCOFJnOE0wNS0yamZWdzQzVkZJWnpBZkw3VmQwSi16N1lLUjlVPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IlNoYXJpZiIsImZhbWlseV9uYW1lIjoiSGFzYW4iLCJpYXQiOjE3NDY1NDYxNTEsImV4cCI6MTc0NjU0OTc1MSwianRpIjoiZjUwNDYwYWZiMzlkMjQwNDIwZDgzN2RhZWY4MmM1Y2IyMWU2YWVmMSJ9.uOuxDHpdrsa952YiSz1NFxgGHkVVRVNat2J2v3qK6smHoZEiSvBZ0Is6S7zgx_78bYw2TuQzdNIZlJlstZAEncpIY73qCelxNV6bD31LV7qeh50uMoDV4lT2qGFGqbE9auFz9JCxrrVj55MKb6WujWkoTQM7bKO_SiUBeIPCGNhXo1e2JlXu10nrrirYhmOHNm2cJ2zj8PA_9C_Py9VFlo1h1AliNhUXwVoja9rXxrhX2Y2iZMl1IUV4u2yHwPprYmHtlQWacDJLT6CKyEi4qGJpX7iC0ojXyS4Pxn-Et4dpie2TdsqJOFTR2p5_8ogvfUQV23dg9YG-XYbvogXcCw";
        SimpleUserModel simpleUserModel = googleIdTokenVerifier.verifyIdToken(idToken);
        assertNotNull(simpleUserModel);
        assertEquals("Sharif Hasan", simpleUserModel.getName());
    }
}