name: Build and Release APK and AAR

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      FLUTTER_BUILD_MODE: release
      FLUTTER_VERSION_NAME: 1.0.0
      FLUTTER_VERSION_CODE: 1
      FLUTTER_MIN_SDK_VERSION: 21
      FLUTTER_TARGET_SDK_VERSION: 34
      FLUTTER_COMPILE_SDK_VERSION: 34

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Flutter
      - name: Set up Flutter
        id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: 'stable'
          cache: false

      # Configure Flutter environment
      - name: Configure Flutter environment
        run: |
          # Remove any existing local.properties
          rm -f android/local.properties
          # Write new local.properties with dynamic paths
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties
          echo "flutter.buildMode=$FLUTTER_BUILD_MODE" >> android/local.properties
          echo "flutter.versionName=$FLUTTER_VERSION_NAME" >> android/local.properties
          echo "flutter.versionCode=$FLUTTER_VERSION_CODE" >> android/local.properties
          echo "flutter.minSdkVersion=$FLUTTER_MIN_SDK_VERSION" >> android/local.properties
          echo "flutter.targetSdkVersion=$FLUTTER_TARGET_SDK_VERSION" >> android/local.properties
          echo "flutter.compileSdkVersion=$FLUTTER_COMPILE_SDK_VERSION" >> android/local.properties
          # Verify local.properties content
          echo "Contents of local.properties:"
          cat android/local.properties
          # Verify Flutter SDK path
          echo "Flutter SDK path: $FLUTTER_HOME"
          ls -la $FLUTTER_HOME
        env:
          FLUTTER_HOME: ${{ steps.flutter-action.outputs.FLUTTER_HOME || '/opt/hostedtoolcache/flutter/3.22.1-stable/x64' }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

      # Install Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip -q commandlinetools.zip -d $ANDROID_SDK_ROOT
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/latest
          yes | $ANDROID_SDK_ROOT/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-${FLUTTER_COMPILE_SDK_VERSION}" "build-tools;${FLUTTER_COMPILE_SDK_VERSION}.0.0"
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Install jq for JSON validation
      - name: Install jq
        run: sudo apt-get install -y jq

      # Validate google-services.json
      - name: Validate google-services.json
        run: |
          if [ -f android/app/google-services.json ]; then
            jq . android/app/google-services.json > /dev/null || { echo "Invalid JSON in google-services.json"; cat android/app/google-services.json; exit 1; }
          else
            echo "google-services.json not found in android/app/"
            exit 1
          fi
        shell: bash

      # Build APK
      - name: Build APK
        run: flutter build apk --release --stacktrace

      # Build AAR
      - name: Build AAR
        run: flutter build aar --release --stacktrace

      # Create release and upload artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/host/outputs/repo/**/*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
