name: Build and Deploy to Azure Container Apps

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - deploy/azure

env:
  DOCKER_IMAGE: iishanto/jobhunterbackend
  AZURE_RESOURCE_GROUP: iishanto
  AZURE_CONTAINER_APP_NAME: jobhunterbackend
  AZURE_LOCATION: westus2
  AZURE_CONTAINER_APP_ENV: managedEnvironment-iishanto-bc4e

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Debug Azure Login (optional, remove after verification)
      - name: Debug Azure Login
        run: |
          az account show --query "{name:name, id:id}" -o tsv || echo "Failed to retrieve account details"
          az account list --query "[].{name:name, id:id}" -o tsv || echo "No subscriptions found"

      # Build and push Docker image
      - name: Build and push Docker image
        env:
          TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${TAG} .
          docker push ${{ env.DOCKER_IMAGE }}:${TAG}

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        env:
          TAG: ${{ github.sha }}
        run: |
          # Note: --os-type is not needed for Azure Container Apps as it only supports Linux containers.
          # Ensure the Docker image (${{ env.DOCKER_IMAGE }}:${TAG}) is Linux-based.
          az containerapp update \
            --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.DOCKER_IMAGE }}:${TAG} \
