name: Build and Deploy to Azure Container Apps

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - deploy/azure

env:
  DOCKER_IMAGE: iishanto/jobhunterbackend
  AZURE_RESOURCE_GROUP: iishanto
  AZURE_CONTAINER_APP_NAME: jobhunterbackend
  AZURE_LOCATION: westus2
  AZURE_CONTAINER_APP_ENV: managedEnvironment-iishanto-bc4e

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # Build and push Docker image
      - name: Build Docker image
        env:
          TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${TAG} .
